[package]
name = "image-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde_json = "1.0.133"
vercel_runtime = "1.1.3"
opendal = { version = "0.50.2", features = ["services-vercel-blob"] }

[[bin]]
name = "index"
path = "api/index.rs"
